### ISSUE TITLE
a couple of odd choices

### ISSUE THREAD

**Issue by selfagency** [fnando/vscode-linter#1]
thanks for making this. but i'm wondering, why are the default config files for eslint set to prettier? it should be eslint config files. also, why is it linting the console/log window?

**Comment by fnando** [comment]
Definitely a bug. Let me fix it! :)

**Comment by fnando** [comment]
Just released v0.0.8. Should be available on Marketplace soon.

**Comment by selfagency** [comment]
It's also linting `settings.json` and then keeping it in the Problems pane once it's closed. Any time you reopen it, it adds another one.

![CleanShot 2021-07-23 at 07 54 30](https://user-images.githubusercontent.com/2541728/126778221-050adb32-f5c6-433d-aa03-129ad1892076.png)

**Comment by fnando** [comment]
The stacking issue is odd: I'm definitely clearing any existing panels before rendering it again. I'll take a look.

As for json linting: I released 0.0.9 with only runs eslint against `.js`, `.jsx`, `.ts`, `.tsx` files from now on.
