### ISSUE TITLE
No linters found for "sql"

### ISSUE THREAD

**Issue by zephyrpathsofglory** [fnando/vscode-linter#16]
Hello:

I have `sqlfluff` installed but when I save my `postgres` migration file with `.sql` extension, linter reports `No linters found for "sql"`.

Does it need extra configuration? What should I do to work it around? Please lend a hand!

**Comment by fnando** [comment]
The language matching is not made to extensions, but rather to how VSCode detects the document (via document.languageId). What does the `linter` panel shows under the `Output` tab?

**Comment by fnando** [comment]
Ah, one thing you can do is setting `fille.associations` to map `.sql` files to Postgres.

```json
{
  "file.associations": {
    "*.sql": "postgres"
  }
}
```

I've been using https://marketplace.visualstudio.com/items?itemName=ckolkman.vscode-postgres for syntax highlighting, so if you save your files as `*.psql` or `*.pgpsql`, you won't need to manually map the extension to it.
