### ISSUE TITLE
Not finding linter in Windows without `.exe`

### ISSUE THREAD

**Issue by giggio** [fnando/vscode-linter#17]
I just got this error:

```
[10/5/2022, 8:27:19 PM] The yamllint binary couldn't be found within $PATH: [
  // omitted for brevity...
  "C:\\Users\\giovanni\\scoop\\apps\\python310\\current\\Scripts",
  // omitted for brevity...  
]
```

I do have the binary at `C:\Users\giovanni\scoop\apps\python310\current\Scripts`, it is named `yamllint.exe`.

It works if I set the config as follows (all I am adding is the `.exe`:

```json5
"linter.linters": {
    "yamllint": {
        "command": [
            "yamllint.exe", // <-- see the .exe
            "--format",
            "parsable",
            [
                "$config",
                "--config-file",
                "$config"
            ],
            "-"
        ]
    }
}
```

If I remove `.exe` from this custom config the same error shows up, confirming the problem. It seems to not be able to find `.exe` on Windows, which is something that works on the OS.

**Comment by fnando** [comment]
I'm trying to handle this on ec5e76bd32399345b2a7dd22b1fdda3f68507090 and 75d2fdd0a50611a173597d6ecc024751004562a3. It adds all permutations of `$PATHEXT` (defaults to `.exe`) to the search on Windows and uses the first binary that's found.

**Comment by fnando** [comment]
Just released v0.0.14. I'll close this, but please report back in case this release doesn't fix the issue.

**Comment by giggio** [comment]
@fnando I just tried it without the config and it is working now, thanks!

**Comment by fnando** [comment]
Awesome! Thanks for confirming it!
