### ISSUE TITLE
Disable linter

### ISSUE THREAD

**Issue by asbjornu** [fnando/vscode-linter#2]
In the documentation it says I can disable linters as such:

```json
{
  "linter.linters": {
    "ruby": {
      "enabled": false
    }
  }
}
```

I've tried adding the above to VSCode's `settings.json`, but that didn't have any effect. Where and how is Linter supposed to be configured?

**Comment by fnando** [comment]
Yeah, that's the right place. Maybe you need to restart VSCode? I think results are being cached, but I didn't update the documentation to mention that. Sorry!

**Comment by asbjornu** [comment]
I've both restarted and updated VSCode and disabled and enabled the extension without any luck. I want to disable Ruby linting because it's not respecting the settings of `.rubocop.yml` (in particular its `Exclude` section). If the Ruby linter respected `.rubocop.yml` configuration, I wouldn't need to disable it.

**Comment by fnando** [comment]
The ruby linter is just running the ruby interpreter. It doesn't support any kind of configuration.

```
cat samples/file.rb | ruby -wc
-:7: warning: assigned but unused variable - b
-:5: warning: assigned but unused variable - a
Syntax OK
```

[These are my VSCode settings](https://gist.github.com/fnando/079760139439943438fb88e51a3a24bd#file-settings-json-L61-L68). As you can see in the screenshot below, it's respecting my settings and not showing any ruby or reek warnings.

![CleanShot 2021-07-23 at 13 16 57@2x](https://user-images.githubusercontent.com/3009/126836941-18c89574-da48-4215-aad3-e3932e13a29d.png)

Here's the same file, but with linters enabled.

![CleanShot 2021-07-23 at 13 17 50@2x](https://user-images.githubusercontent.com/3009/126837011-0badb0ea-0644-4d66-bb8b-0cac484852ac.png)

I hope that helps!

**Comment by asbjornu** [comment]
Weird. This is what I see when I enable Linter:

<img width="690" alt="Block has too many lines" src="https://user-images.githubusercontent.com/12283/127641980-56c9c139-6ace-4e78-8f1e-33b23b3f657c.png">

As you can see, this error comes from RuboCop. Disabling Linter makes this error go away. But IIRC, Linter does not support RuboCop so this error does can't come from Linter? 🤔

**Comment by jtmkrueger** [comment]
@asbjornu 
> As you can see, this error comes from RuboCop. Disabling Linter makes this error go away. But IIRC, Linter does not support RuboCop so this error does can't come from Linter? 🤔

It does support rubocop. You need to add
```
    "linter.linters": {
      "ruby": {
        "enabled": false
      },
      "rubocop": {
        "enabled": false
      }
    },
```
to disable both of them

**Comment by asbjornu** [comment]
@jtmkrueger, setting the suggested `rubocop` section in `settings.json` and restarting VS Code indeed seems to have turned off RuboCop linting. Thanks!
