### ISSUE TITLE
Add DBT "jinja-sql" files to sqlfluff linter

### ISSUE THREAD

**Issue by Startouf** [fnando/vscode-linter#21]
DBT is a popular framework for data modeling and transformations, is is built on SQL with jinja macros, and their official plugin extension records a file type "Jinja SQL", which can be linted with sqlfluff with the DBT templater

[Sqlfluff officially supports DBT](https://docs.sqlfluff.com/en/stable/configuration.html#dbt-project-configuration)

```
# .sqlfluff
[sqlfluff]
dialect = bigquery
templater = dbt
```

It would be great to add this compatibility out of the box when installing the extension

**Comment by fnando** [comment]
Just released v0.0.16 with this. :)
