### ISSUE TITLE
Custom linter doesn't work without "configFiles" property

### ISSUE THREAD

**Issue by rubikonx9** [fnando/vscode-linter#6]
I have set up a simple custom linter according to the instructions [here](https://github.com/fnando/vscode-linter/blob/main/docs/creating-linters.md).

It worked just fine until I removed the `configFiles` property from the configuration in `package.json`.
When it's missing, the plugin builds, get loaded (it's listed in "available linters" log entry), but it never gets executed. No errors or warnings are issues anywhere (or at least in all places I searched for).

This is very counter-intuitive - some simple linters may not require or even support configuration files.

Adding an empty list: `"configFiles": []` resolves the issue, but I spent quite some time to find it out.

**Comment by fnando** [comment]
I've added a note about this on that document. I'll try to handle this better through other mechanisms (maybe a linter for linters?)
