### ISSUE TITLE
Question: How to specify PyLint custom link for error documentation?

### ISSUE THREAD

**Issue by DmytroSokhach** [fnando/vscode-linter#7]
Current pylint documentation link is not very useful, but I like the Quick FIx navigation (no need to search for every error manually in browser)

For example r1705:
This warning doesn't have the page: http://pylint-messages.wikidot.com/messages:r1705
So I want it to navigate to that site: https://vald-phoenix.github.io/pylint-errors/plerr/errors/refactoring/R1705

**Comment by fnando** [comment]
This is tricky, because looks I can't sent to that domain due to the category (refactoring, error, etc). If you provide a better site that can show a better description based on the error code, I can change it.
