### ISSUE TITLE
Docs request: clarify how to change the configuration file for a given linter

### ISSUE THREAD

**Issue by olivierlefloch** [fnando/vscode-linter#8]
I'm not seeing clearly laid out in the documentation how I should go about tweaking the global lint rules for a given linter (say to have `yamllint` ignore `document-start` globally or use a different default `line-length`)?

**Comment by ryanmerolle** [comment]
Can you override global configuration per git repo?

**Comment by fnando** [comment]
@olivierlefloch hey, sorry for not answer this earlier.

For pretty every single linter, all you have to do is following the linter's configuration. In this case (`yamllint`), you need to [create a `.yamllint.yml` or `.yamllint.yml`](https://yamllint.readthedocs.io/en/stable/configuration.html) file at the project's root directory.
